//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaggerheartCharsheet.Core.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaggerheartCharsheet.Core.Resources.Locales.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancestry.
        /// </summary>
        internal static string Section_BasicInfo_Ancestry {
            get {
                return ResourceManager.GetString("Section_BasicInfo_Ancestry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Section_BasicInfo_Level {
            get {
                return ResourceManager.GetString("Section_BasicInfo_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronouns.
        /// </summary>
        internal static string Section_BasicInfo_Pronouns {
            get {
                return ResourceManager.GetString("Section_BasicInfo_Pronouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subclass.
        /// </summary>
        internal static string Section_BasicInfo_Subclass {
            get {
                return ResourceManager.GetString("Section_BasicInfo_Subclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Sheet_Name {
            get {
                return ResourceManager.GetString("Sheet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        internal static string Sheet_Name_Placeholder {
            get {
                return ResourceManager.GetString("Sheet_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foundation.
        /// </summary>
        internal static string SubclassCardTier_Foundation {
            get {
                return ResourceManager.GetString("SubclassCardTier_Foundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastery.
        /// </summary>
        internal static string SubclassCardTier_Mastery {
            get {
                return ResourceManager.GetString("SubclassCardTier_Mastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        internal static string SubclassCardTier_Specialization {
            get {
                return ResourceManager.GetString("SubclassCardTier_Specialization", resourceCulture);
            }
        }
    }
}
