//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaggerheartCharsheet.Core.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Core202509 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Core202509() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaggerheartCharsheet.Core.Resources.Locales.Core202509", typeof(Core202509).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seraph.
        /// </summary>
        internal static string Class_Seraph {
            get {
                return ResourceManager.GetString("Class_Seraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splendor.
        /// </summary>
        internal static string Domain_Splendor {
            get {
                return ResourceManager.GetString("Domain_Splendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string Domain_Valor {
            get {
                return ResourceManager.GetString("Domain_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DivineWielder.
        /// </summary>
        internal static string Subclass_Seraph_DivineWielder {
            get {
                return ResourceManager.GetString("Subclass_Seraph_DivineWielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align:center;&quot;&gt;Spellcast: STRENGTH&lt;/p&gt;
        ///
        ///Spirit Weapon: When you have an equipped weapon with a range of Melee or Very Close, it can fly from your hand to attack an adversary within Close range and then return to you. You can mark a Stress to target an additional adversary within range with the same attack roll.
        ///
        ///Sparing Touch: Once per long rest, touch a creature and clear 2 Hit Points or 2 Stress from them..
        /// </summary>
        internal static string Subclass_Seraph_DivineWielder_Foundation_Description {
            get {
                return ResourceManager.GetString("Subclass_Seraph_DivineWielder_Foundation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WingedSentinel.
        /// </summary>
        internal static string Subclass_Seraph_WingedSentinel {
            get {
                return ResourceManager.GetString("Subclass_Seraph_WingedSentinel", resourceCulture);
            }
        }
    }
}
